# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.IntegerField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=50)),
                ('head_of_department', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_name', models.CharField(max_length=50)),
                ('usn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Department')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='usn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Department'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Course'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='usn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Student'),
        ),
    ]
